# Generated by Django 3.1.7 on 2021-03-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='enrolled',
            field=models.BooleanField(default=False, verbose_name='Зачислен'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='orden_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='django_applications.test', verbose_name='Код ордена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruit',
            name='trials',
            field=models.JSONField(blank=True, null=True, verbose_name='Испытание'),
        ),
        migrations.AddField(
            model_name='sith',
            name='recruits',
            field=models.ManyToManyField(blank=True, to='django_applications.Recruit', verbose_name='Рекркты'),
        ),
        migrations.AlterField(
            model_name='test',
            name='orden_code',
            field=models.SlugField(max_length=8, unique=True, verbose_name='Код ордена'),
        ),
    ]
